# CMake generated Testfile for 
# Source directory: C:/Users/tom20/Desktop/noson-2.12.24/tests
# Build directory: C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[check_compressor]=] "C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests/Debug/check_compressor.exe")
  set_tests_properties([=[check_compressor]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/tom20/Desktop/noson-2.12.24/tests" _BACKTRACE_TRIPLES "C:/Users/tom20/Desktop/noson-2.12.24/tests/cmake/UnitTestProject.cmake;40;add_test;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;62;unittest_project;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[check_compressor]=] "C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests/Release/check_compressor.exe")
  set_tests_properties([=[check_compressor]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/tom20/Desktop/noson-2.12.24/tests" _BACKTRACE_TRIPLES "C:/Users/tom20/Desktop/noson-2.12.24/tests/cmake/UnitTestProject.cmake;40;add_test;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;62;unittest_project;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[check_compressor]=] "C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests/MinSizeRel/check_compressor.exe")
  set_tests_properties([=[check_compressor]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/tom20/Desktop/noson-2.12.24/tests" _BACKTRACE_TRIPLES "C:/Users/tom20/Desktop/noson-2.12.24/tests/cmake/UnitTestProject.cmake;40;add_test;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;62;unittest_project;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[check_compressor]=] "C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests/RelWithDebInfo/check_compressor.exe")
  set_tests_properties([=[check_compressor]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/tom20/Desktop/noson-2.12.24/tests" _BACKTRACE_TRIPLES "C:/Users/tom20/Desktop/noson-2.12.24/tests/cmake/UnitTestProject.cmake;40;add_test;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;62;unittest_project;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;0;")
else()
  add_test([=[check_compressor]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[check_soap_parser]=] "C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests/Debug/check_soap_parser.exe")
  set_tests_properties([=[check_soap_parser]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/tom20/Desktop/noson-2.12.24/tests" _BACKTRACE_TRIPLES "C:/Users/tom20/Desktop/noson-2.12.24/tests/cmake/UnitTestProject.cmake;40;add_test;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;63;unittest_project;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[check_soap_parser]=] "C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests/Release/check_soap_parser.exe")
  set_tests_properties([=[check_soap_parser]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/tom20/Desktop/noson-2.12.24/tests" _BACKTRACE_TRIPLES "C:/Users/tom20/Desktop/noson-2.12.24/tests/cmake/UnitTestProject.cmake;40;add_test;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;63;unittest_project;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[check_soap_parser]=] "C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests/MinSizeRel/check_soap_parser.exe")
  set_tests_properties([=[check_soap_parser]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/tom20/Desktop/noson-2.12.24/tests" _BACKTRACE_TRIPLES "C:/Users/tom20/Desktop/noson-2.12.24/tests/cmake/UnitTestProject.cmake;40;add_test;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;63;unittest_project;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[check_soap_parser]=] "C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests/RelWithDebInfo/check_soap_parser.exe")
  set_tests_properties([=[check_soap_parser]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/tom20/Desktop/noson-2.12.24/tests" _BACKTRACE_TRIPLES "C:/Users/tom20/Desktop/noson-2.12.24/tests/cmake/UnitTestProject.cmake;40;add_test;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;63;unittest_project;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;0;")
else()
  add_test([=[check_soap_parser]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[check_intrinsic]=] "C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests/Debug/check_intrinsic.exe")
  set_tests_properties([=[check_intrinsic]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/tom20/Desktop/noson-2.12.24/tests" _BACKTRACE_TRIPLES "C:/Users/tom20/Desktop/noson-2.12.24/tests/cmake/UnitTestProject.cmake;40;add_test;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;64;unittest_project;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[check_intrinsic]=] "C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests/Release/check_intrinsic.exe")
  set_tests_properties([=[check_intrinsic]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/tom20/Desktop/noson-2.12.24/tests" _BACKTRACE_TRIPLES "C:/Users/tom20/Desktop/noson-2.12.24/tests/cmake/UnitTestProject.cmake;40;add_test;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;64;unittest_project;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[check_intrinsic]=] "C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests/MinSizeRel/check_intrinsic.exe")
  set_tests_properties([=[check_intrinsic]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/tom20/Desktop/noson-2.12.24/tests" _BACKTRACE_TRIPLES "C:/Users/tom20/Desktop/noson-2.12.24/tests/cmake/UnitTestProject.cmake;40;add_test;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;64;unittest_project;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[check_intrinsic]=] "C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests/RelWithDebInfo/check_intrinsic.exe")
  set_tests_properties([=[check_intrinsic]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/tom20/Desktop/noson-2.12.24/tests" _BACKTRACE_TRIPLES "C:/Users/tom20/Desktop/noson-2.12.24/tests/cmake/UnitTestProject.cmake;40;add_test;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;64;unittest_project;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;0;")
else()
  add_test([=[check_intrinsic]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[check_builtin]=] "C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests/Debug/check_builtin.exe")
  set_tests_properties([=[check_builtin]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/tom20/Desktop/noson-2.12.24/tests" _BACKTRACE_TRIPLES "C:/Users/tom20/Desktop/noson-2.12.24/tests/cmake/UnitTestProject.cmake;40;add_test;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;65;unittest_project;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[check_builtin]=] "C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests/Release/check_builtin.exe")
  set_tests_properties([=[check_builtin]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/tom20/Desktop/noson-2.12.24/tests" _BACKTRACE_TRIPLES "C:/Users/tom20/Desktop/noson-2.12.24/tests/cmake/UnitTestProject.cmake;40;add_test;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;65;unittest_project;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[check_builtin]=] "C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests/MinSizeRel/check_builtin.exe")
  set_tests_properties([=[check_builtin]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/tom20/Desktop/noson-2.12.24/tests" _BACKTRACE_TRIPLES "C:/Users/tom20/Desktop/noson-2.12.24/tests/cmake/UnitTestProject.cmake;40;add_test;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;65;unittest_project;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[check_builtin]=] "C:/Users/tom20/Desktop/noson-2.12.24/build_vc/tests/RelWithDebInfo/check_builtin.exe")
  set_tests_properties([=[check_builtin]=] PROPERTIES  WORKING_DIRECTORY "C:/Users/tom20/Desktop/noson-2.12.24/tests" _BACKTRACE_TRIPLES "C:/Users/tom20/Desktop/noson-2.12.24/tests/cmake/UnitTestProject.cmake;40;add_test;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;65;unittest_project;C:/Users/tom20/Desktop/noson-2.12.24/tests/CMakeLists.txt;0;")
else()
  add_test([=[check_builtin]=] NOT_AVAILABLE)
endif()
