#!/usr/bin/env python3
"""
把 resources/ 目录下的所有 .svg 嵌入成一个 C++ 源文件。
用法: python3 embed_resources.py <svg_dir> <output_cpp>
"""
import os
import sys

def main():
    if len(sys.argv) != 3:
        print("Usage: embed_resources.py <svg_dir> <output_cpp>")
        return 1

    svg_dir = sys.argv[1]
    out_cpp = sys.argv[2]

    if not os.path.isdir(svg_dir):
        print(f"Directory not found: {svg_dir}")
        return 1

    entries = []
    for f in sorted(os.listdir(svg_dir)):
        if not f.lower().endswith('.svg'):
            continue
        name = f[:-4]  # 去掉 .svg
        path = os.path.join(svg_dir, f)
        with open(path, 'r', encoding='utf-8') as fp:
            content = fp.read()
        entries.append((name, content))

    with open(out_cpp, 'w', encoding='utf-8') as fp:
        fp.write('// AUTO-GENERATED by tools/embed_resources.py. DO NOT EDIT.\n')
        fp.write('#include "embedded_resources.h"\n')
        fp.write('#include <unordered_map>\n\n')
        fp.write('namespace {\n')
        fp.write('const std::unordered_map<std::string, std::string> g_embedded = {\n')
        for name, content in entries:
            # 用原始字符串字面量，避免转义
            fp.write(f'    {{"{name}", R"RAWSVG({content})RAWSVG"}},\n')
        fp.write('};\n')
        fp.write('} // namespace\n\n')
        fp.write('const std::string* GetEmbeddedResource(const std::string& name) {\n')
        fp.write('    auto it = g_embedded.find(name);\n')
        fp.write('    return it != g_embedded.end() ? &it->second : nullptr;\n')
        fp.write('}\n')

    print(f'Generated {out_cpp}: {len(entries)} resources')
    return 0

if __name__ == '__main__':
    sys.exit(main())
